### PR TITLE
Fixed issues preventing tests to pass on Python 3

### PR DESCRIPTION
**Pull request by gforcada**
master branch coming from https://github.com/pyrenees/plone.uuid to add python 3.5 compatibility.

@datakurre I cleanup the commits to remove buildout/boostrap and all that. Is it worth keeping?

### CODE REVIEW

**Comment by jensens** [comment]
I'am not sure if this is considered as a bugfix (like "doesnt run on python 3") or as a feature (runs now on python 3).  I tend to the latter and this would need - according to semantic versioning) a version bumb on the minor level to 1.1.0.

**Comment by jensens** [comment]
i consider this bugfix like

**Comment by gforcada** [comment]
@jensens thanks for merging, but don't merge more code from pyrenees pull requests. Sorry I didn't make it clear on the pull requests...

If we are merging code that fixes the code to run on py35 but we are not testing against it... well kind of pointless. I'm working on fixing that :-)

**Comment by jensens** [comment]
well, the changes in there are fine. +1 for having those packages tested in jenkins. good work!

**Pull request merged**
